# See https://www.gitpod.io/docs/multi-repo-workspaces
additionalRepositories:
  - url: https://github.com/koalaman/ace
    # checkoutLocation is relative to /workspaces
    checkoutLocation: ace

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - env:
      # This is used in gitpod's default apache2.conf
      APACHE_DOCROOT_IN_REPO: "."
    init: |
      cd /workspace/ace
      npm install
      node ./Makefile.dryice.js

      cd ../shellcheck.net
      ln -s ../ace/build/src libace
    command: |
      sudo apt-get update
      sudo apt-get install -y shellcheck
      apachectl start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8001
    onOpen: open-preview
